### ISSUE TITLE
Catch up with ddiatmb's fork

### ISSUE THREAD

**Issue by archonic** [kanet77/togglv8#4]
You've had a pending pull request for the reports API for years. ddiatmb's fork is the furthest ahead.

Is there some other up to date Ruby Toggl API wrapper everyone else knows about?

**Comment by kanet77** [comment]
You're right. It's time to update this library.

When itaymendel made a PR in November of 2013 I was too busy dealing with a heavy workload and a car crash. It fell through the cracks. This project has been on my mind lately because it is the oldest item on my TODO list.  Looks like some others have made some progress.

I also want to reorganize the library into a gem and replace `test.rb` and `atest.rb` with rspec tests.

I'll try to make some time for this soon. Anyone have PRs to contribute?

**Comment by archonic** [comment]
Reorganizing the tests is a good idea. @ddiatmb's fork includes the @itaymendel's work and more, so if that master branch was pulled, that would be a good restarting point. I'm not sure if any API aspects are missing, but completing them would be the next step if it isn't. Let me know if there's anything I can help with.

**Comment by ppawlikmb** [comment]
The state of @ddiatmb fork is:
- Reports API is included (at the point where the open PR is)
- some project_groups functions are added (although it's hard to say if it's a proper implementation as these functions are undocumented in API docs)
- it's gemified

Basically it's two or three forks merged together with some minor additions and fixes.

**Comment by kanet77** [comment]
## togglv8 gem (0.2.0) released!

I converted my code to a gem ([togglv8](https://rubygems.org/gems/togglv8) on rubygems) and added rspec tests. It has about 90% test coverage along happy paths and is well organized for the addition of more specs.

I spent some time refactoring and the code is much better organized. Please take a look for yourself. I'm open to suggestions or pull requests.

### Next Steps

I made a `TogglV8` module with an internal `TogglV8::API` class with the intention of adding `TogglV8::Reports`. I plan to include the Reports code written by others.

I see @itaymendel created a `TogglCon` module and included it in `Toggl ` and `TogglReports`. I might follow that convention if anyone can explain why it's a better direction. Any opinions on the matter?

These are the forks I'm aware of. Any others?
* https://github.com/ddiatmb/togglv8 (most up-to-date?)
* https://github.com/archonic/togglv8
* https://github.com/ppawlikmb/togglv8
* https://github.com/madcowley/togglv8

Please take a look if you have some time.

And thanks for your efforts on this!

**Comment by itaymendel** [comment]
@kanet77 I had to move the methods to a module so that i can reuse them. the decision to put it in a module, was because at the time it was the fastest way for me to use them, without refactoring other parts of the gem. The only important part of the code is `reportsV2.rb` file. I wanted to add it without changing too much of the code.

Perhaps now is a good time to do some refactoring :+1: 

Anyway, I'm glad to see that this gets done, and I hope that you are feeling well!

**Comment by archonic** [comment]
Great! My fork only had a fix for namespacing on the test files. Eventually I'll be using something close to the full API. Currently I'm most concerned about the reports side of things. I'll give this a spin.

**Comment by kanet77** [comment]
I can't believe it's been an entire year. I no longer use Toggl or write Ruby code. Sorry that this was on the back burner for so long.

TogglV8 now supports the Reports API. Any comments, PRs, or suggestions are welcome.

Cheers!
